### PR TITLE
Remove upper bounds and add stack support

### PR DESCRIPTION
**Pull request by tiago-loureiro**
This changeset allows us to use more recent versions of GHC as well as stack

### CODE REVIEW

**Comment by Ericson2314** [comment]
Removing upper bounds is bad for Cabal and not necessary for Stack.

**Comment by tiago-loureiro** [comment]
> and not necessary for Stack.

Could you please elaborate on this one? If I need to use, for instance, `attoparsec-0.13` in my project I am unable to do so if I want to use your library and will end up with an error such as:

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for multihash-0.1.3:
    attoparsec-0.13.0.0 must match >=0.12 && <0.13 (latest applicable is 0.12.1.6)

Plan construction failed.
```

Perhaps just relaxing then the upper bound as they are currently too strict? I am happy to provide another cabal file that contains upper bounds that still work with the current code.

**Comment by lukehoersten** [comment]
Thanks for the PR. It is, in fact, incorrect to remove upper bounds. Just bump them to the latest versions in the stack resolver you've selected. Check out the PVP for more info: https://pvp.haskell.org

**Comment by CMCDragonkai** [comment]
What is the procedure in stack to use this in GHC 8.x?

**Comment by CMCDragonkai** [comment]
@tiago-loureiro Thanks for doing this PR, we're using this in haskell-multiaddr https://github.com/MatrixAI/haskell-multiaddr And this dependency is being propagated to haskell-multistream, and the current version constraints is preventing usage of some iostream features.

**Comment by tiago-loureiro** [comment]
I have tested my PR with both `lts-8.15 - GHC 8.0.2` and `lts-6.33 - GHC 7.10.3` and they both build fine.
It mostly just relaxed the upper bounds for base, attoparsec and io-streams.

**Comment by plintX** [comment]
@LukeHoersten any updates on merging this?

**Comment by ghost** [comment]
@LukeHoersten Any updates on merging this?

**Comment by lukehoersten** [comment]
Sorry didn't realize the upper bounds were added back in. Thanks for the PR.

**Pull request merged**
